 name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Install basic packages
  apt:
    name:
      - curl
      - wget
      - unzip
      - git
      - vim
      - net-tools
      - python3-pymysql
    state: present
